[package]
name = "ragout"
version = "0.1.0"
edition = "2021"
description = "Terminal raw mode utilities"
license = "MIT"

[dependencies]
crossterm = "0.27.0"

[[test]]
name = "basic_input"
path = "src/lib.rs"

[[example]]
name = "default"
path = "examples/default.rs"


