[package]
name = "flaxen"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"

# [lib]
# name = "lib"
# path = "src/lib.rs"

[[example]]
name = "flaxen"
path = "examples/main.rs"


