[package]
name = "ragout"
version = "0.2.0"
edition = "2021"
description = "Terminal raw mode utilities"
license = "MIT"
repository = "https://github.com/uraneko/ragout"
readme = "README.md"
keywords = ["terminal", "raw_mode", "cli"]
categories = ["command-line-interface"]
exclude = ["resources/logs/", "Cargo.lock"]

[dependencies]
crossterm = "0.27.0"

[[example]]
name = "default"
path = "examples/default.rs"


