[package]
name = "ragout"
version = "0.1.0"
edition = "2021"
description = "Terminal raw mode utilities"
license = "MIT"
repo = "https://github.com/uraneko/ragout"
readme = "README.md"
keywords = ["terminal", "raw mode", "cli"]
categories = ["command-line-interface"]
exclude = ["resources/logs/", "Cargo.lock"]

[dependencies]
crossterm = "0.27.0"

[[test]]
name = "basic_input"
path = "src/lib.rs"

[[example]]
name = "default"
path = "examples/default.rs"


