name: Labeler

on: 
   pull_request_target:

jobs: 
  labeler: 
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      pull-request: write
    steps: 
    - uses: actions/labeler@v5
      with: 
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

